SharedLibrary(target='test/lib/libla', source=['lib/laconn.c', 'lib/lamsg.c'])

# RPATH add paths to search for shared libraries when executing (linux only)
Program(target='main', source='test/main.c', LIBS=['la'], LIBPATH=['test/lib'], RPATH=['test/lib'])
# https://stackoverflow.com/questions/24564078/scons-executable-shared-library-in-project-directory

# Documentation session could mention it: 4.2