SharedLibrary(target='test/lib/libla', source=['lib/laconn.c', 'lib/lamsg.c'])

# Linking shared library with executable
Program(target='main', source='test/main.c', LIBS=['la'], LIBPATH=['test/lib'])
# During execution it will search the shared library
#   In windows, will search at same location as the executable
#   In linux, will search at locations like /usr/lib